env:
  global:
    - CC_TEST_REPORTER_ID=$CODECLIMATE_REPO_TOKEN
language: node_js
node_js:
  - "stable"
before_script:
  - yarn
  - yarn global add codeclimate-test-reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: yarn test
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
